SLUG="hello-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 0 Hello World" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="nice-regular-box-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 1 Nice Regular Box" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="convert-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 2 Convert" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="ultron-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 3 Ultron" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="giza-gas"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 4 Giza and Words" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="jagged-array-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 5 Jagged Array" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="optimization-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 6 Modern Optimization" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="caching-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 7 Caching" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="elf-loader-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Homework 8 Elf Loader" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
SLUG="x16-simple-c"; gh teacher assignment add cs-wwu-247 csci247-spring-2027 ${SLUG} --name "Final Project X16" --template cs-wwu-247/${SLUG} --tests ${SLUG}/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json

