SLUG="hello-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 0 Hello World" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="nice-regular-box-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 1 Nice Regular Box" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="compleat-adventure-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 2 Compleat Adventure" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="rational-numbers-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 3 Rational Numbers" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="infinite-playlist-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 4 Infinite Playlist" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="jagged-array-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 5 Jagged Array" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="collections-framework-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 6 Collections Framework" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="around-the-world-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 7 Around The World" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="reverse-polish-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Homework 8 Reverse Polish" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="snake-ship-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Midterm Snake Ship" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="pair-star-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Midterm Snake Ship" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="chicken-shack-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Midterm Snake Ship" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="reuse-list-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Midterm Reuse List" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="sentinel-list-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Final Sentinel List" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
SLUG="complex-numbers-java"; gh teacher assignment add cs-wwu-145 csci145-fall-2026 ${SLUG} --name "Final Complex Numbers" --template cs-wwu-145/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json


