gh teacher assignment add cs-wwu-367 csci367-fall-2026 hello-c --template cs-wwu-367/hello-c --name "Homework 0 Hello World" --template cs-wwu-367/hello-c --tests hello-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 telephone-py --template cs-wwu-367/telephone-py --name "Homework 1 Telephone Switching" --template cs-wwu-367/telephone-py --tests telephone-py/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 aloha-c --template cs-wwu-367/aloha-c --name "Homework 2 Aloha" --template cs-wwu-367/aloha-c --tests aloha-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 spanning-tree-c --template cs-wwu-367/spanning-tree-c --name "Homework 3 Spanning Tree" --template cs-wwu-367/spanning-tree-c --tests spanning-tree-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 link-state-routing-java --template cs-wwu-367/link-state-routing-java --name "Homework 4 Link State Routing" --template cs-wwu-367/link-state-routing-java --tests link-state-routing-java/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 ip-fragmentation-reassembly-c --template cs-wwu-367/ip-fragmentation-reassembly-c --name "Homework 5 IP Fragmentation and Reassembly" --template cs-wwu-367/ip-fragmentation-reassembly-c --tests ip-fragmentation-reassembly-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 ancient-book-curses-c --template cs-wwu-367/ancient-book-curses-c --name "Homework 6 Ancient Book Curses" --template cs-wwu-367/ancient-book-curses-c --tests ancient-book-curses-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 http-proxy-cpp --template cs-wwu-367/http-proxy-cpp --name "Homework 7 HTTP Proxy" --template cs-wwu-367/http-proxy-cpp --tests http-proxy-cpp/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
gh teacher assignment add cs-wwu-367 csci367-fall-2026 tcp-sim-c --template cs-wwu-367/tcp-sim-c --name "Final Project Tcp Sim" --template cs-wwu-367/tcp-sim-c --tests tcp-sim-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-367.json
