gh teacher assignment add cs-wwu-247 csci247-spring-2027 hello-c --name "Homework 0 Hello World" --template cs-wwu-247/hello-c --tests hello-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 nice-regular-box-c --name "Homework 1 Nice Regular Box" --template cs-wwu-247/nice-regular-box-c --tests nice-regular-box-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 convert-c --name "Homework 2 Convert" --template cs-wwu-247/convert-c --tests convert-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 ultron-c --name "Homework 3 Ultron" --template cs-wwu-247/ultron-c --tests ultron-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 giza-gas --name "Homework 4 Giza" --template cs-wwu-247/giza-gas --tests giza-gas/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 jagged-array-c --name "Homework 5 Jagged Array" --template cs-wwu-247/jagged-array-c --tests jagged-array-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 optimization-c --name "Homework 6 Modern Optimization" --template cs-wwu-247/optimization-c --tests optimization-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 caching-c --name "Homework 7 Caching" --template cs-wwu-247/caching-c --tests caching-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 elf-loader-c --name "Homework 8 Elf Loader" --template cs-wwu-247/elf-loader-c --tests elf-loader-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
gh teacher assignment add cs-wwu-247 csci247-spring-2027 x16-simple-c --name "Final Project X16" --template cs-wwu-247/x16-simple-c --tests x16-simple-c/tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-247.json
