gh teacher assignment add cs-wwu-145 csci145-fall-2026 hello-java --name "Homework 0 Hello World" --template cs-wwu-145/hello-java --tests hello-java/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 nice-regular-box-java --name "Homework 1 Nice Regular Box" --template cs-wwu-145/nice-regular-box-java --tests nice-regular-box-java/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 compleat-adventure-java --name "Homework 2 Compleat Adventure" --template cs-wwu-145/compleat-adventure-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json

gh teacher assignment add cs-wwu-145 csci145-fall-2026 rational-numbers-java --name "Homework 3 Rational Numbers" --template cs-wwu-145/rational-numbers-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 infinite-playlist-java --name "Homework 4 Infinite Playlists" --template cs-wwu-145/infinite-playlist-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 jagged-array-java --name "Homework 5 Jagged Array" --template cs-wwu-145/jagged-array-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 collections-framework-java --name "Homework 6 Collections Framework" --template cs-wwu-145/collections-framework-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 around-the-world-java --name "Homework 7 Around The World" --template cs-wwu-145/around-the-world-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 reverse-polish-java --name "Homework 8 Reverse Polish" --template cs-wwu-145/reverse-polish-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json


gh teacher assignment add cs-wwu-145 csci145-fall-2026 snake-ship-java --name "Midterm Snake Ship" --template cs-wwu-145/snake-ship-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 pair-star-java --name "Midterm Pair Star" --template cs-wwu-145/pair-star-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 sentinel-list-java --name "Final Sentinel List" --template cs-wwu-145/sentinel-list-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 complex-numbers-java --name "Final Complex Numbers" --template cs-wwu-145/complex-numbers-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 chicken-shack-java --name "Midterm Chicken Shack" --template cs-wwu-145/chicken-shack-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
gh teacher assignment add cs-wwu-145 csci145-fall-2026 reuse-list-java --name "Final Reuse List" --template cs-wwu-145/reuse-list-java --tests compleat-adventure-java/Tests/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-145.json
