SLUG="hello-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 0 Hello World" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="reverse-polish-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 1 Reverse Polish" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="bloom-filter-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 2 Maybe Present" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="radix-sort-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 3 Snobby Sort" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="skip-list-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 4 Skipping Through Lists" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="trie-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 5 Predicting The Future" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="parse-tree-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 6 Parse Trees" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="gap-buffer-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 7 Gaps" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="graph-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Homework 7 Going Places With Graphs" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="rope-editor-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Final Project Rope Editor" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="index-link-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Midterm Index Link" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="priority-list-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Midterm Priority List" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json
SLUG="quick-tree-java"; gh teacher assignment add cs-wwu-305 csci305-qq-yyyy ${SLUG} --name "Final Quick Tree" --template cs-wwu-305/${SLUG} --tests ${SLUG}/Test/tests.json --runtime ~/Teaching/Autograder/runtimes/runtime-305.json

